name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-go@5
        with:
          go-version: "1.22.x"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: "v1.59"
          skip-go-installation: true
