name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48
          # Remove this when upgrading golanci-lint
          # https://github.com/golangci/golangci-lint/issues/2997#issuecomment-1216864452
          args: --timeout=5m
